name: Aggiorna Classifica

on:
  push:
    branches:
      - main # o la tua branch principale

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Aggiorna Classifica
        run: |
          # Aggiungi qui il codice per aggiornare highscores.json
          # (ad esempio, esegui il tuo script Node.js)
      - name: Commit e push
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Aggiorna classifica"
